import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <header className="bg-gray-800 text-white p-4">
            <div className="container mx-auto flex justify-between items-center">
              <Link href="/" className="text-2xl font-bold">
                OrdinalsBot App
              </Link>
              <nav className="space-x-4">
                <Link href="/" className="hover:text-gray-300">
                  Home
                </Link>
                <Link href="/balance" className="hover:text-gray-300">
                  Balance
                </Link>
                <Link href="/order" className="hover:text-gray-300">
                  Order
                </Link>
              </nav>
            </div>
          </header>

          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
